package com.ol.house.model;

import java.util.ArrayList;
import java.util.List;

public class HouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public HouseExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andHousesIsNull() {
            addCriterion("houses is null");
            return (Criteria) this;
        }

        public Criteria andHousesIsNotNull() {
            addCriterion("houses is not null");
            return (Criteria) this;
        }

        public Criteria andHousesEqualTo(String value) {
            addCriterion("houses =", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesNotEqualTo(String value) {
            addCriterion("houses <>", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesGreaterThan(String value) {
            addCriterion("houses >", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesGreaterThanOrEqualTo(String value) {
            addCriterion("houses >=", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesLessThan(String value) {
            addCriterion("houses <", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesLessThanOrEqualTo(String value) {
            addCriterion("houses <=", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesLike(String value) {
            addCriterion("houses like", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesNotLike(String value) {
            addCriterion("houses not like", value, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesIn(List<String> values) {
            addCriterion("houses in", values, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesNotIn(List<String> values) {
            addCriterion("houses not in", values, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesBetween(String value1, String value2) {
            addCriterion("houses between", value1, value2, "houses");
            return (Criteria) this;
        }

        public Criteria andHousesNotBetween(String value1, String value2) {
            addCriterion("houses not between", value1, value2, "houses");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureIsNull() {
            addCriterion("area_architecture is null");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureIsNotNull() {
            addCriterion("area_architecture is not null");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureEqualTo(Double value) {
            addCriterion("area_architecture =", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureNotEqualTo(Double value) {
            addCriterion("area_architecture <>", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureGreaterThan(Double value) {
            addCriterion("area_architecture >", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureGreaterThanOrEqualTo(Double value) {
            addCriterion("area_architecture >=", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureLessThan(Double value) {
            addCriterion("area_architecture <", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureLessThanOrEqualTo(Double value) {
            addCriterion("area_architecture <=", value, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureIn(List<Double> values) {
            addCriterion("area_architecture in", values, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureNotIn(List<Double> values) {
            addCriterion("area_architecture not in", values, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureBetween(Double value1, Double value2) {
            addCriterion("area_architecture between", value1, value2, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaArchitectureNotBetween(Double value1, Double value2) {
            addCriterion("area_architecture not between", value1, value2, "areaArchitecture");
            return (Criteria) this;
        }

        public Criteria andAreaRoomIsNull() {
            addCriterion("area_room is null");
            return (Criteria) this;
        }

        public Criteria andAreaRoomIsNotNull() {
            addCriterion("area_room is not null");
            return (Criteria) this;
        }

        public Criteria andAreaRoomEqualTo(Double value) {
            addCriterion("area_room =", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomNotEqualTo(Double value) {
            addCriterion("area_room <>", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomGreaterThan(Double value) {
            addCriterion("area_room >", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomGreaterThanOrEqualTo(Double value) {
            addCriterion("area_room >=", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomLessThan(Double value) {
            addCriterion("area_room <", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomLessThanOrEqualTo(Double value) {
            addCriterion("area_room <=", value, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomIn(List<Double> values) {
            addCriterion("area_room in", values, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomNotIn(List<Double> values) {
            addCriterion("area_room not in", values, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomBetween(Double value1, Double value2) {
            addCriterion("area_room between", value1, value2, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andAreaRoomNotBetween(Double value1, Double value2) {
            addCriterion("area_room not between", value1, value2, "areaRoom");
            return (Criteria) this;
        }

        public Criteria andGongTIsNull() {
            addCriterion("gong_t is null");
            return (Criteria) this;
        }

        public Criteria andGongTIsNotNull() {
            addCriterion("gong_t is not null");
            return (Criteria) this;
        }

        public Criteria andGongTEqualTo(String value) {
            addCriterion("gong_t =", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTNotEqualTo(String value) {
            addCriterion("gong_t <>", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTGreaterThan(String value) {
            addCriterion("gong_t >", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTGreaterThanOrEqualTo(String value) {
            addCriterion("gong_t >=", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTLessThan(String value) {
            addCriterion("gong_t <", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTLessThanOrEqualTo(String value) {
            addCriterion("gong_t <=", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTLike(String value) {
            addCriterion("gong_t like", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTNotLike(String value) {
            addCriterion("gong_t not like", value, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTIn(List<String> values) {
            addCriterion("gong_t in", values, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTNotIn(List<String> values) {
            addCriterion("gong_t not in", values, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTBetween(String value1, String value2) {
            addCriterion("gong_t between", value1, value2, "gongT");
            return (Criteria) this;
        }

        public Criteria andGongTNotBetween(String value1, String value2) {
            addCriterion("gong_t not between", value1, value2, "gongT");
            return (Criteria) this;
        }

        public Criteria andIsResidenceIsNull() {
            addCriterion("is_residence is null");
            return (Criteria) this;
        }

        public Criteria andIsResidenceIsNotNull() {
            addCriterion("is_residence is not null");
            return (Criteria) this;
        }

        public Criteria andIsResidenceEqualTo(Integer value) {
            addCriterion("is_residence =", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceNotEqualTo(Integer value) {
            addCriterion("is_residence <>", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceGreaterThan(Integer value) {
            addCriterion("is_residence >", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_residence >=", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceLessThan(Integer value) {
            addCriterion("is_residence <", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceLessThanOrEqualTo(Integer value) {
            addCriterion("is_residence <=", value, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceIn(List<Integer> values) {
            addCriterion("is_residence in", values, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceNotIn(List<Integer> values) {
            addCriterion("is_residence not in", values, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceBetween(Integer value1, Integer value2) {
            addCriterion("is_residence between", value1, value2, "isResidence");
            return (Criteria) this;
        }

        public Criteria andIsResidenceNotBetween(Integer value1, Integer value2) {
            addCriterion("is_residence not between", value1, value2, "isResidence");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNull() {
            addCriterion("house_type is null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNotNull() {
            addCriterion("house_type is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeEqualTo(String value) {
            addCriterion("house_type =", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotEqualTo(String value) {
            addCriterion("house_type <>", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThan(String value) {
            addCriterion("house_type >", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("house_type >=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThan(String value) {
            addCriterion("house_type <", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThanOrEqualTo(String value) {
            addCriterion("house_type <=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLike(String value) {
            addCriterion("house_type like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotLike(String value) {
            addCriterion("house_type not like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIn(List<String> values) {
            addCriterion("house_type in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotIn(List<String> values) {
            addCriterion("house_type not in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeBetween(String value1, String value2) {
            addCriterion("house_type between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotBetween(String value1, String value2) {
            addCriterion("house_type not between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andDoorplateIsNull() {
            addCriterion("doorplate is null");
            return (Criteria) this;
        }

        public Criteria andDoorplateIsNotNull() {
            addCriterion("doorplate is not null");
            return (Criteria) this;
        }

        public Criteria andDoorplateEqualTo(String value) {
            addCriterion("doorplate =", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateNotEqualTo(String value) {
            addCriterion("doorplate <>", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateGreaterThan(String value) {
            addCriterion("doorplate >", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateGreaterThanOrEqualTo(String value) {
            addCriterion("doorplate >=", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateLessThan(String value) {
            addCriterion("doorplate <", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateLessThanOrEqualTo(String value) {
            addCriterion("doorplate <=", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateLike(String value) {
            addCriterion("doorplate like", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateNotLike(String value) {
            addCriterion("doorplate not like", value, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateIn(List<String> values) {
            addCriterion("doorplate in", values, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateNotIn(List<String> values) {
            addCriterion("doorplate not in", values, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateBetween(String value1, String value2) {
            addCriterion("doorplate between", value1, value2, "doorplate");
            return (Criteria) this;
        }

        public Criteria andDoorplateNotBetween(String value1, String value2) {
            addCriterion("doorplate not between", value1, value2, "doorplate");
            return (Criteria) this;
        }

        public Criteria andIsPlacementIsNull() {
            addCriterion("is_placement is null");
            return (Criteria) this;
        }

        public Criteria andIsPlacementIsNotNull() {
            addCriterion("is_placement is not null");
            return (Criteria) this;
        }

        public Criteria andIsPlacementEqualTo(Integer value) {
            addCriterion("is_placement =", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementNotEqualTo(Integer value) {
            addCriterion("is_placement <>", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementGreaterThan(Integer value) {
            addCriterion("is_placement >", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_placement >=", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementLessThan(Integer value) {
            addCriterion("is_placement <", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementLessThanOrEqualTo(Integer value) {
            addCriterion("is_placement <=", value, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementIn(List<Integer> values) {
            addCriterion("is_placement in", values, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementNotIn(List<Integer> values) {
            addCriterion("is_placement not in", values, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementBetween(Integer value1, Integer value2) {
            addCriterion("is_placement between", value1, value2, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsPlacementNotBetween(Integer value1, Integer value2) {
            addCriterion("is_placement not between", value1, value2, "isPlacement");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNull() {
            addCriterion("is_new is null");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNotNull() {
            addCriterion("is_new is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEqualTo(Integer value) {
            addCriterion("is_new =", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotEqualTo(Integer value) {
            addCriterion("is_new <>", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThan(Integer value) {
            addCriterion("is_new >", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_new >=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThan(Integer value) {
            addCriterion("is_new <", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThanOrEqualTo(Integer value) {
            addCriterion("is_new <=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewIn(List<Integer> values) {
            addCriterion("is_new in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotIn(List<Integer> values) {
            addCriterion("is_new not in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewBetween(Integer value1, Integer value2) {
            addCriterion("is_new between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotBetween(Integer value1, Integer value2) {
            addCriterion("is_new not between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andDecorationIsNull() {
            addCriterion("decoration is null");
            return (Criteria) this;
        }

        public Criteria andDecorationIsNotNull() {
            addCriterion("decoration is not null");
            return (Criteria) this;
        }

        public Criteria andDecorationEqualTo(String value) {
            addCriterion("decoration =", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationNotEqualTo(String value) {
            addCriterion("decoration <>", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationGreaterThan(String value) {
            addCriterion("decoration >", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationGreaterThanOrEqualTo(String value) {
            addCriterion("decoration >=", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationLessThan(String value) {
            addCriterion("decoration <", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationLessThanOrEqualTo(String value) {
            addCriterion("decoration <=", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationLike(String value) {
            addCriterion("decoration like", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationNotLike(String value) {
            addCriterion("decoration not like", value, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationIn(List<String> values) {
            addCriterion("decoration in", values, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationNotIn(List<String> values) {
            addCriterion("decoration not in", values, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationBetween(String value1, String value2) {
            addCriterion("decoration between", value1, value2, "decoration");
            return (Criteria) this;
        }

        public Criteria andDecorationNotBetween(String value1, String value2) {
            addCriterion("decoration not between", value1, value2, "decoration");
            return (Criteria) this;
        }

        public Criteria andPingYueIsNull() {
            addCriterion("ping_yue is null");
            return (Criteria) this;
        }

        public Criteria andPingYueIsNotNull() {
            addCriterion("ping_yue is not null");
            return (Criteria) this;
        }

        public Criteria andPingYueEqualTo(String value) {
            addCriterion("ping_yue =", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueNotEqualTo(String value) {
            addCriterion("ping_yue <>", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueGreaterThan(String value) {
            addCriterion("ping_yue >", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueGreaterThanOrEqualTo(String value) {
            addCriterion("ping_yue >=", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueLessThan(String value) {
            addCriterion("ping_yue <", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueLessThanOrEqualTo(String value) {
            addCriterion("ping_yue <=", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueLike(String value) {
            addCriterion("ping_yue like", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueNotLike(String value) {
            addCriterion("ping_yue not like", value, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueIn(List<String> values) {
            addCriterion("ping_yue in", values, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueNotIn(List<String> values) {
            addCriterion("ping_yue not in", values, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueBetween(String value1, String value2) {
            addCriterion("ping_yue between", value1, value2, "pingYue");
            return (Criteria) this;
        }

        public Criteria andPingYueNotBetween(String value1, String value2) {
            addCriterion("ping_yue not between", value1, value2, "pingYue");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNull() {
            addCriterion("buy_price is null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNotNull() {
            addCriterion("buy_price is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceEqualTo(Double value) {
            addCriterion("buy_price =", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotEqualTo(Double value) {
            addCriterion("buy_price <>", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThan(Double value) {
            addCriterion("buy_price >", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("buy_price >=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThan(Double value) {
            addCriterion("buy_price <", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThanOrEqualTo(Double value) {
            addCriterion("buy_price <=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIn(List<Double> values) {
            addCriterion("buy_price in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotIn(List<Double> values) {
            addCriterion("buy_price not in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceBetween(Double value1, Double value2) {
            addCriterion("buy_price between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotBetween(Double value1, Double value2) {
            addCriterion("buy_price not between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andPayInfoIsNull() {
            addCriterion("pay_info is null");
            return (Criteria) this;
        }

        public Criteria andPayInfoIsNotNull() {
            addCriterion("pay_info is not null");
            return (Criteria) this;
        }

        public Criteria andPayInfoEqualTo(String value) {
            addCriterion("pay_info =", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoNotEqualTo(String value) {
            addCriterion("pay_info <>", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoGreaterThan(String value) {
            addCriterion("pay_info >", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoGreaterThanOrEqualTo(String value) {
            addCriterion("pay_info >=", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoLessThan(String value) {
            addCriterion("pay_info <", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoLessThanOrEqualTo(String value) {
            addCriterion("pay_info <=", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoLike(String value) {
            addCriterion("pay_info like", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoNotLike(String value) {
            addCriterion("pay_info not like", value, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoIn(List<String> values) {
            addCriterion("pay_info in", values, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoNotIn(List<String> values) {
            addCriterion("pay_info not in", values, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoBetween(String value1, String value2) {
            addCriterion("pay_info between", value1, value2, "payInfo");
            return (Criteria) this;
        }

        public Criteria andPayInfoNotBetween(String value1, String value2) {
            addCriterion("pay_info not between", value1, value2, "payInfo");
            return (Criteria) this;
        }

        public Criteria andTransCompanyIsNull() {
            addCriterion("trans_company is null");
            return (Criteria) this;
        }

        public Criteria andTransCompanyIsNotNull() {
            addCriterion("trans_company is not null");
            return (Criteria) this;
        }

        public Criteria andTransCompanyEqualTo(String value) {
            addCriterion("trans_company =", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyNotEqualTo(String value) {
            addCriterion("trans_company <>", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyGreaterThan(String value) {
            addCriterion("trans_company >", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("trans_company >=", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyLessThan(String value) {
            addCriterion("trans_company <", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyLessThanOrEqualTo(String value) {
            addCriterion("trans_company <=", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyLike(String value) {
            addCriterion("trans_company like", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyNotLike(String value) {
            addCriterion("trans_company not like", value, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyIn(List<String> values) {
            addCriterion("trans_company in", values, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyNotIn(List<String> values) {
            addCriterion("trans_company not in", values, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyBetween(String value1, String value2) {
            addCriterion("trans_company between", value1, value2, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransCompanyNotBetween(String value1, String value2) {
            addCriterion("trans_company not between", value1, value2, "transCompany");
            return (Criteria) this;
        }

        public Criteria andTransPriceIsNull() {
            addCriterion("trans_price is null");
            return (Criteria) this;
        }

        public Criteria andTransPriceIsNotNull() {
            addCriterion("trans_price is not null");
            return (Criteria) this;
        }

        public Criteria andTransPriceEqualTo(Double value) {
            addCriterion("trans_price =", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceNotEqualTo(Double value) {
            addCriterion("trans_price <>", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceGreaterThan(Double value) {
            addCriterion("trans_price >", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("trans_price >=", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceLessThan(Double value) {
            addCriterion("trans_price <", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceLessThanOrEqualTo(Double value) {
            addCriterion("trans_price <=", value, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceIn(List<Double> values) {
            addCriterion("trans_price in", values, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceNotIn(List<Double> values) {
            addCriterion("trans_price not in", values, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceBetween(Double value1, Double value2) {
            addCriterion("trans_price between", value1, value2, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPriceNotBetween(Double value1, Double value2) {
            addCriterion("trans_price not between", value1, value2, "transPrice");
            return (Criteria) this;
        }

        public Criteria andTransPayIsNull() {
            addCriterion("trans_pay is null");
            return (Criteria) this;
        }

        public Criteria andTransPayIsNotNull() {
            addCriterion("trans_pay is not null");
            return (Criteria) this;
        }

        public Criteria andTransPayEqualTo(String value) {
            addCriterion("trans_pay =", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayNotEqualTo(String value) {
            addCriterion("trans_pay <>", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayGreaterThan(String value) {
            addCriterion("trans_pay >", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayGreaterThanOrEqualTo(String value) {
            addCriterion("trans_pay >=", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayLessThan(String value) {
            addCriterion("trans_pay <", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayLessThanOrEqualTo(String value) {
            addCriterion("trans_pay <=", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayLike(String value) {
            addCriterion("trans_pay like", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayNotLike(String value) {
            addCriterion("trans_pay not like", value, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayIn(List<String> values) {
            addCriterion("trans_pay in", values, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayNotIn(List<String> values) {
            addCriterion("trans_pay not in", values, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayBetween(String value1, String value2) {
            addCriterion("trans_pay between", value1, value2, "transPay");
            return (Criteria) this;
        }

        public Criteria andTransPayNotBetween(String value1, String value2) {
            addCriterion("trans_pay not between", value1, value2, "transPay");
            return (Criteria) this;
        }

        public Criteria andHousePersonIsNull() {
            addCriterion("house_person is null");
            return (Criteria) this;
        }

        public Criteria andHousePersonIsNotNull() {
            addCriterion("house_person is not null");
            return (Criteria) this;
        }

        public Criteria andHousePersonEqualTo(String value) {
            addCriterion("house_person =", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonNotEqualTo(String value) {
            addCriterion("house_person <>", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonGreaterThan(String value) {
            addCriterion("house_person >", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonGreaterThanOrEqualTo(String value) {
            addCriterion("house_person >=", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonLessThan(String value) {
            addCriterion("house_person <", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonLessThanOrEqualTo(String value) {
            addCriterion("house_person <=", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonLike(String value) {
            addCriterion("house_person like", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonNotLike(String value) {
            addCriterion("house_person not like", value, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonIn(List<String> values) {
            addCriterion("house_person in", values, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonNotIn(List<String> values) {
            addCriterion("house_person not in", values, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonBetween(String value1, String value2) {
            addCriterion("house_person between", value1, value2, "housePerson");
            return (Criteria) this;
        }

        public Criteria andHousePersonNotBetween(String value1, String value2) {
            addCriterion("house_person not between", value1, value2, "housePerson");
            return (Criteria) this;
        }

        public Criteria andMoveApplyIsNull() {
            addCriterion("move_apply is null");
            return (Criteria) this;
        }

        public Criteria andMoveApplyIsNotNull() {
            addCriterion("move_apply is not null");
            return (Criteria) this;
        }

        public Criteria andMoveApplyEqualTo(String value) {
            addCriterion("move_apply =", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyNotEqualTo(String value) {
            addCriterion("move_apply <>", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyGreaterThan(String value) {
            addCriterion("move_apply >", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyGreaterThanOrEqualTo(String value) {
            addCriterion("move_apply >=", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyLessThan(String value) {
            addCriterion("move_apply <", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyLessThanOrEqualTo(String value) {
            addCriterion("move_apply <=", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyLike(String value) {
            addCriterion("move_apply like", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyNotLike(String value) {
            addCriterion("move_apply not like", value, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyIn(List<String> values) {
            addCriterion("move_apply in", values, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyNotIn(List<String> values) {
            addCriterion("move_apply not in", values, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyBetween(String value1, String value2) {
            addCriterion("move_apply between", value1, value2, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApplyNotBetween(String value1, String value2) {
            addCriterion("move_apply not between", value1, value2, "moveApply");
            return (Criteria) this;
        }

        public Criteria andMoveApproverIsNull() {
            addCriterion("move_approver is null");
            return (Criteria) this;
        }

        public Criteria andMoveApproverIsNotNull() {
            addCriterion("move_approver is not null");
            return (Criteria) this;
        }

        public Criteria andMoveApproverEqualTo(String value) {
            addCriterion("move_approver =", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverNotEqualTo(String value) {
            addCriterion("move_approver <>", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverGreaterThan(String value) {
            addCriterion("move_approver >", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverGreaterThanOrEqualTo(String value) {
            addCriterion("move_approver >=", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverLessThan(String value) {
            addCriterion("move_approver <", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverLessThanOrEqualTo(String value) {
            addCriterion("move_approver <=", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverLike(String value) {
            addCriterion("move_approver like", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverNotLike(String value) {
            addCriterion("move_approver not like", value, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverIn(List<String> values) {
            addCriterion("move_approver in", values, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverNotIn(List<String> values) {
            addCriterion("move_approver not in", values, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverBetween(String value1, String value2) {
            addCriterion("move_approver between", value1, value2, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoveApproverNotBetween(String value1, String value2) {
            addCriterion("move_approver not between", value1, value2, "moveApprover");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountIsNull() {
            addCriterion("money_account is null");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountIsNotNull() {
            addCriterion("money_account is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountEqualTo(String value) {
            addCriterion("money_account =", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountNotEqualTo(String value) {
            addCriterion("money_account <>", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountGreaterThan(String value) {
            addCriterion("money_account >", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountGreaterThanOrEqualTo(String value) {
            addCriterion("money_account >=", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountLessThan(String value) {
            addCriterion("money_account <", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountLessThanOrEqualTo(String value) {
            addCriterion("money_account <=", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountLike(String value) {
            addCriterion("money_account like", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountNotLike(String value) {
            addCriterion("money_account not like", value, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountIn(List<String> values) {
            addCriterion("money_account in", values, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountNotIn(List<String> values) {
            addCriterion("money_account not in", values, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountBetween(String value1, String value2) {
            addCriterion("money_account between", value1, value2, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andMoneyAccountNotBetween(String value1, String value2) {
            addCriterion("money_account not between", value1, value2, "moneyAccount");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIsNull() {
            addCriterion("property_fee is null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIsNotNull() {
            addCriterion("property_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeEqualTo(String value) {
            addCriterion("property_fee =", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotEqualTo(String value) {
            addCriterion("property_fee <>", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeGreaterThan(String value) {
            addCriterion("property_fee >", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeGreaterThanOrEqualTo(String value) {
            addCriterion("property_fee >=", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeLessThan(String value) {
            addCriterion("property_fee <", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeLessThanOrEqualTo(String value) {
            addCriterion("property_fee <=", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeLike(String value) {
            addCriterion("property_fee like", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotLike(String value) {
            addCriterion("property_fee not like", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIn(List<String> values) {
            addCriterion("property_fee in", values, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotIn(List<String> values) {
            addCriterion("property_fee not in", values, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeBetween(String value1, String value2) {
            addCriterion("property_fee between", value1, value2, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotBetween(String value1, String value2) {
            addCriterion("property_fee not between", value1, value2, "propertyFee");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 06 11:12:14 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}