package com.ol.house.model;

public class House {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.id
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.location
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.houses
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String houses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.area_architecture
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Double areaArchitecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.area_room
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Double areaRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.gong_t
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String gongT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.is_residence
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Integer isResidence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.house_type
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String houseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.doorplate
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String doorplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.is_placement
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Integer isPlacement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.is_new
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Integer isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.decoration
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String decoration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.ping_yue
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String pingYue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.buy_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Double buyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.pay_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String payInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.trans_company
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String transCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.trans_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private Double transPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.trans_pay
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String transPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.house_person
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String housePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.move_apply
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String moveApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.move_approver
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String moveApprover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.money_account
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String moneyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_info.property_fee
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    private String propertyFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.id
     *
     * @return the value of house_info.id
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.id
     *
     * @param id the value for house_info.id
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.location
     *
     * @return the value of house_info.location
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.location
     *
     * @param location the value for house_info.location
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.houses
     *
     * @return the value of house_info.houses
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getHouses() {
        return houses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.houses
     *
     * @param houses the value for house_info.houses
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setHouses(String houses) {
        this.houses = houses == null ? null : houses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.area_architecture
     *
     * @return the value of house_info.area_architecture
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Double getAreaArchitecture() {
        return areaArchitecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.area_architecture
     *
     * @param areaArchitecture the value for house_info.area_architecture
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setAreaArchitecture(Double areaArchitecture) {
        this.areaArchitecture = areaArchitecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.area_room
     *
     * @return the value of house_info.area_room
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Double getAreaRoom() {
        return areaRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.area_room
     *
     * @param areaRoom the value for house_info.area_room
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setAreaRoom(Double areaRoom) {
        this.areaRoom = areaRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.gong_t
     *
     * @return the value of house_info.gong_t
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getGongT() {
        return gongT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.gong_t
     *
     * @param gongT the value for house_info.gong_t
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setGongT(String gongT) {
        this.gongT = gongT == null ? null : gongT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.is_residence
     *
     * @return the value of house_info.is_residence
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Integer getIsResidence() {
        return isResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.is_residence
     *
     * @param isResidence the value for house_info.is_residence
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setIsResidence(Integer isResidence) {
        this.isResidence = isResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.house_type
     *
     * @return the value of house_info.house_type
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.house_type
     *
     * @param houseType the value for house_info.house_type
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.doorplate
     *
     * @return the value of house_info.doorplate
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getDoorplate() {
        return doorplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.doorplate
     *
     * @param doorplate the value for house_info.doorplate
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setDoorplate(String doorplate) {
        this.doorplate = doorplate == null ? null : doorplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.is_placement
     *
     * @return the value of house_info.is_placement
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Integer getIsPlacement() {
        return isPlacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.is_placement
     *
     * @param isPlacement the value for house_info.is_placement
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setIsPlacement(Integer isPlacement) {
        this.isPlacement = isPlacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.is_new
     *
     * @return the value of house_info.is_new
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Integer getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.is_new
     *
     * @param isNew the value for house_info.is_new
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.decoration
     *
     * @return the value of house_info.decoration
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getDecoration() {
        return decoration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.decoration
     *
     * @param decoration the value for house_info.decoration
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setDecoration(String decoration) {
        this.decoration = decoration == null ? null : decoration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.ping_yue
     *
     * @return the value of house_info.ping_yue
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getPingYue() {
        return pingYue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.ping_yue
     *
     * @param pingYue the value for house_info.ping_yue
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setPingYue(String pingYue) {
        this.pingYue = pingYue == null ? null : pingYue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.buy_price
     *
     * @return the value of house_info.buy_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Double getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.buy_price
     *
     * @param buyPrice the value for house_info.buy_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.pay_info
     *
     * @return the value of house_info.pay_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getPayInfo() {
        return payInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.pay_info
     *
     * @param payInfo the value for house_info.pay_info
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setPayInfo(String payInfo) {
        this.payInfo = payInfo == null ? null : payInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.trans_company
     *
     * @return the value of house_info.trans_company
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getTransCompany() {
        return transCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.trans_company
     *
     * @param transCompany the value for house_info.trans_company
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setTransCompany(String transCompany) {
        this.transCompany = transCompany == null ? null : transCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.trans_price
     *
     * @return the value of house_info.trans_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public Double getTransPrice() {
        return transPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.trans_price
     *
     * @param transPrice the value for house_info.trans_price
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setTransPrice(Double transPrice) {
        this.transPrice = transPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.trans_pay
     *
     * @return the value of house_info.trans_pay
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getTransPay() {
        return transPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.trans_pay
     *
     * @param transPay the value for house_info.trans_pay
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setTransPay(String transPay) {
        this.transPay = transPay == null ? null : transPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.house_person
     *
     * @return the value of house_info.house_person
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getHousePerson() {
        return housePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.house_person
     *
     * @param housePerson the value for house_info.house_person
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setHousePerson(String housePerson) {
        this.housePerson = housePerson == null ? null : housePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.move_apply
     *
     * @return the value of house_info.move_apply
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getMoveApply() {
        return moveApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.move_apply
     *
     * @param moveApply the value for house_info.move_apply
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setMoveApply(String moveApply) {
        this.moveApply = moveApply == null ? null : moveApply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.move_approver
     *
     * @return the value of house_info.move_approver
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getMoveApprover() {
        return moveApprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.move_approver
     *
     * @param moveApprover the value for house_info.move_approver
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setMoveApprover(String moveApprover) {
        this.moveApprover = moveApprover == null ? null : moveApprover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.money_account
     *
     * @return the value of house_info.money_account
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getMoneyAccount() {
        return moneyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.money_account
     *
     * @param moneyAccount the value for house_info.money_account
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setMoneyAccount(String moneyAccount) {
        this.moneyAccount = moneyAccount == null ? null : moneyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_info.property_fee
     *
     * @return the value of house_info.property_fee
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public String getPropertyFee() {
        return propertyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_info.property_fee
     *
     * @param propertyFee the value for house_info.property_fee
     *
     * @mbg.generated Thu Aug 06 11:12:14 CST 2020
     */
    public void setPropertyFee(String propertyFee) {
        this.propertyFee = propertyFee == null ? null : propertyFee.trim();
    }
}